CREATE TABLE EMPLOYEES
AS
SELECT *FROM
HR.EMPLOYEES;

-- USER DEFINED FUNTIONS

CREATE OR REPLACE FUNCTION CAL_EXP(EID NUMBER)
RETURN NUMBER
AS
EXPER NUMBER;

BEGIN
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0) INTO EXPER
FROM EMPLOYEES
WHERE EMPLOYEE_ID = EID ;
RETURN EXPER ;
END;

--FUNCTION CALLING
set serveroutput ON
DECLARE
EMP_EXPER NUMBER ;
BEGIN
EMP_EXPER := CAL_EXP(101);
DBMS_OUTPUT.PUT_LINE(EMP_EXPER);
END;

--====================================================================
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION CALCULATE_EXPER(EID NUMBER)
RETURN NUMBER
AS
TOTAL_EXP NUMBER;

BEGIN
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0) INTO TOTAL_EXP
FROM EMPLOYEES
WHERE EMPLOYEE_ID=EID;

RETURN TOTAL_EXP;
END;

--FUNCTION CALLING
SET SERVEROUTPUT ON
DECLARE
EMP_EX NUMBER;
BEGIN
 EMP_EX:=CALCULATE_EXPER(100);
 DBMS_OUTPUT.PUT_LINE(EMP_EX);
END;
--===================================================================












